// memberPost = Faculty_Coordinator, Student_Coordinator, Student_Head, Student_Team

import {
  sanidhya,
  sharda_soni,
  vinay_marwal,
  aryan,
  harsh,
  manasvi,
  dinesh,
  akshat,
  vanshika,
  tanishq,
  hemant,
  mohit,
  viren
} from './assets/index';

const sntTeamMember = [
  // Faculty Coordinators
  {
    memberName: 'Dr. Sharda Soni',
    memberPost: 'Faculty_Coordinator',
    memberTeam: '',
    memberPhoto: sharda_soni,
    memberRole: 'Head of Department',
    memberDepartment: 'Chemistry',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  {
    memberName: 'Mr. Vinay Marwal',
    memberPost: 'Faculty_Coordinator',
    memberTeam: '',
    memberPhoto: vinay_marwal,
    memberRole: 'Associate Professor',
    memberDepartment: 'Department of Mechanical Engineering',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  // Student Coordinators
  {
    memberName: 'Hemant',
    memberPost: 'Student_Coordinator',
    memberTeam: '',
    memberPhoto: hemant,
    memberRole: 'Student Coordinator',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'ECE',
    memberInsta: 'https://www.instagram.com/_hemant710_?utm_source=qr&igsh=OXV2YWF4eXBxM2xo',
    memberLinkedin: 'https://www.linkedin.com/in/hemant-sarswat-b94643367?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    memberName: 'Aryan Saxena',
    memberPost: 'Student_Coordinator',
    memberTeam: '',
    memberPhoto: aryan,
    memberRole: 'Student Coordinator',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'CSE',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/aryan-saxena-95a285330?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },
  {
    memberName: 'Harsh Maheshwari',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: harsh,
    memberRole: 'Tutor Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'CS-IOT',
    memberInsta: 'https://www.instagram.com/just_harshhhhh?igsh=MXF5ZHI4azFjcGVuMQ==',
    memberLinkedin: 'https://www.linkedin.com/in/harsh-maheshwari-20a55a31b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    memberName: 'Viren Soni',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: viren,
    memberRole: 'Development Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'IT',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/virensoni29/',
  },
  {
    memberName: 'Akshat Singhal',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: akshat,
    memberRole: 'Management Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'IT',
    memberInsta: 'https://www.instagram.com/akshat._.25',
    memberLinkedin: 'http://www.linkedin.com/in/akshat-singhal-841617328',
  },
  {
    memberName: 'Dinesh Ved',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: dinesh,
    memberRole: 'Social Media Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'CE',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/dinesh-ved-ab635130a',
  },
  {
    memberName: 'Mohit Goswami',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: mohit,
    memberRole: 'Social Media Head',
    memberDepartment: '',
    memberYear: 'II yr',
    memberBranch: 'CSE',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/mohit-goswami-697952395?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  {
    memberName: 'Manasvi',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: manasvi,
    memberRole: 'Design Head',
    memberDepartment: '',
    memberYear: 'II yr',
    memberBranch: 'CS-AI',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/manasvi-maheshwari-639605366',
  },
  {
    memberName: 'Tanishq Mittal',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: tanishq,
    memberRole: 'Community Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'IT',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/priyansh-samar-9b5540385?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },
  {
    memberName: 'Vanshika Thadani',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: vanshika,
    memberRole: 'Content Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'CS-AI',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/vanshika-thadani0326',
  },
  // Student Team
  // Development Team
  {
    memberName: 'Arihant Jain',
    memberPost: 'Student_Team',
    memberTeam: 'Development_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/arihant-jain-3071a036a?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },
  {
    memberName: 'Akshat Jain',
    memberPost: 'Student_Team',
    memberTeam: 'Development_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/akshat-jain-19299337a/',
  },
  // Tutor Team
  {
    memberName: 'Charu Jain',
    memberPost: 'Student_Team',
    memberTeam: 'Tutor_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/charu-jain-722503380?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },
  {
    memberName: 'Saanchi Khandelwal',
    memberPost: 'Student_Team',
    memberTeam: 'Tutor_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/saanchi-khandelwal-30a0b53b8?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },
  {
    memberName: 'Shyama Ojha',
    memberPost: 'Student_Team',
    memberTeam: 'Tutor_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/shyama-ojha-a2375b41b?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },

  // Design Team
  {
    memberName: 'Durvisha Raj',
    memberPost: 'Student_Team',
    memberTeam: 'Design_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/durvisha-raj-8609b8429?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },
  {
    memberName: 'Divyansh Shah',
    memberPost: 'Student_Team',
    memberTeam: 'Design_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/divyansh-shah-7a2a93370?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },
  // Content Team
  {
    memberName: 'Mansh',
    memberPost: 'Student_Team',
    memberTeam: 'content_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/mansh-kumar-bb3844373?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },
  {
    memberName: 'Subnidhi Mittal',
    memberPost: 'Student_Team',
    memberTeam: 'content_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/sunidhi-mittal-731147425?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },
  {
    memberName: 'Yachi Gupta',
    memberPost: 'Student_Team',
    memberTeam: 'content_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/yachi-gupta-892537420?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },
  {
    memberName: 'Dinesh Ved',
    memberPost: 'Student_Team',
    memberTeam: 'social_media_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/dinesh-ved-ab635130a',
  },
  {
    memberName: 'Mohit Goswami',
    memberPost: 'Student_Team',
    memberTeam: 'social_media_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/mohit-goswami-697952395?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
  },
  // PR team
  // {
  //   memberName: 'Sarafat Khan',
  //   memberPost: 'Student_Team',
  //   memberTeam: 'PR_social_media',
  //   memberPhoto: '',
  //   memberRole: '',
  //   memberDepartment: '',
  //   memberYear: '',
  //   memberBranch: '',
  //   memberInsta: '',
  //   memberLinkedin: 'https://www.linkedin.com/in/sarafat-khan/',
  // },
  // event team
  {
    memberName: 'Pragya Sharma',
    memberPost: 'Student_Team',
    memberTeam: 'event_team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/pragya-sharma-b5722a387?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },
  {
    memberName: 'Priyansh Samar',
    memberPost: 'Student_Team',
    memberTeam: 'event_team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/priyansh-samar-9b5540385?utm_source=share_via&utm_content=profile&utm_medium=member_android',
  },

];

export { sntTeamMember };
