// memberPost = Faculty_Coordinator, Student_Coordinator, Student_Head, Student_Team

import {
  aditiya,
kshitij,
  Jaideep,
  rishita,
  sanidhya,
  astha,
  yash,
  mehul,
  sharda_soni,
  vinay_marwal
} from './assets/index';

const sntTeamMember = [
  // Faculty Coordinators
  {
    memberName: 'Dr. Sharda Soni',
    memberPost: 'Faculty_Coordinator',
    memberTeam: '',
    memberPhoto: sharda_soni,
    memberRole: 'Head of Department',
    memberDepartment: 'Chemistry',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  {
    memberName: 'Mr. Vinay Marwal',
    memberPost: 'Faculty_Coordinator',
    memberTeam: '',
    memberPhoto: vinay_marwal,
    memberRole: 'Associate Professor',
    memberDepartment: 'Department of Mechanical Engineering',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  // Student Coordinators
  {
    memberName: 'Kshitij Mathur',
    memberPost: 'Student_Coordinator',
    memberTeam: '',
    memberPhoto: kshitij,
    memberRole: 'Student Coordinator',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'CSE',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/kshitijmathur08/',
  },
  {
    memberName: 'Jaideep Singh Chouhan',
    memberPost: 'Student_Coordinator',
    memberTeam: '',
    memberPhoto: Jaideep,
    memberRole: 'Student Coordinator',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'CSE',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/jaideep-singh-chouhan-4537ab302/',
  },
  {
    memberName: 'Rishita Agrawal',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: rishita,
    memberRole: 'Tutor Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'CSE',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/rishita-agrawal-2031692b1',
  },
  {
    memberName: 'Sanidhya Mehra',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: sanidhya,
    memberRole: 'Development Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'CSE',
    memberInsta: 'https://www.instagram.com/sanidhya_mehra_/',
    memberLinkedin: 'https://www.linkedin.com/in/sanidhya-mehra-a0310a25b/',
  },
  {
    memberName: 'Aaditya Bansal',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: aditiya,
    memberRole: 'Management & PR Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'CSE',
    memberInsta: 'https://www.instagram.com/aadityabansal_111/',
    memberLinkedin: 'https://www.linkedin.com/in/aaditya-bansal-aadityabansal111/',
  },
  {
    memberName: 'Yash Bansal',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: yash,
    memberRole: 'Editing Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'CSE',
    memberInsta: 'https://www.instagram.com/_yash_0426/',
    memberLinkedin: 'https://www.linkedin.com/in/yash-bansal-9663a623b',
  },
  {
    memberName: 'Mehul Dangda',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: mehul,
    memberRole: 'Design Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'CSE',
    memberInsta: 'https://www.instagram.com/mehulverse/',
    memberLinkedin: 'https://www.linkedin.com/in/mehuldangda/',
  },
  // {
  //   memberName: 'Priyansh',
  //   memberPost: 'Student_Head',
  //   memberTeam: '',
  //   memberPhoto: priyansh ,
  //   memberRole: 'Social Media/PR Head',
  //   memberDepartment: '',
  //   memberYear: 'III yr',
  //   memberBranch: 'CSE',
  //   memberInsta: 'https://www.instagram.com/priyanshh.77?',
  //   memberLinkedin: 'https://www.linkedin.com/in/priyansh-agrawal-6486b1260',
  // },
  {
    memberName: 'Aastha Sharma',
    memberPost: 'Student_Head',
    memberTeam: '',
    memberPhoto: astha,
    memberRole: 'Content Head',
    memberDepartment: '',
    memberYear: 'III yr',
    memberBranch: 'ECE',
    memberInsta: '',
    memberLinkedin: 'https://linkedin.com/in/aastha-sharma-556aba243',
  },
  // Student Team
  // Development Team
  {
    memberName: 'Viren Soni',
    memberPost: 'Student_Team',
    memberTeam: 'Development_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/virensoni29/',
  },
  // Tutor Team
  {
    memberName: 'Harsh Maheshwari',
    memberPost: 'Student_Team',
    memberTeam: 'Tutor_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  {
    memberName: 'Aryan Saxena',
    memberPost: 'Student_Team',
    memberTeam: 'Tutor_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  {
    memberName: 'Mehul Arya',
    memberPost: 'Student_Team',
    memberTeam: 'Tutor_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  // Design Team
  {
    memberName: 'Manasvi',
    memberPost: 'Student_Team',
    memberTeam: 'Design_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  {
    memberName: 'Hemant',
    memberPost: 'Student_Team',
    memberTeam: 'Design_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  // Content Team
  {
    memberName: 'Aishwarya Hada',
    memberPost: 'Student_Team',
    memberTeam: 'content_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  {
    memberName: 'Vanshika Thadani',
    memberPost: 'Student_Team',
    memberTeam: 'content_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  {
    memberName: 'Mohit Goswami',
    memberPost: 'Student_Team',
    memberTeam: 'editing_Team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  // PR team
  // {
  //   memberName: 'Sarafat Khan',
  //   memberPost: 'Student_Team',
  //   memberTeam: 'PR_social_media',
  //   memberPhoto: '',
  //   memberRole: '',
  //   memberDepartment: '',
  //   memberYear: '',
  //   memberBranch: '',
  //   memberInsta: '',
  //   memberLinkedin: 'https://www.linkedin.com/in/sarafat-khan/',
  // },
  // event team
  {
    memberName: 'Pragya',
    memberPost: 'Student_Team',
    memberTeam: 'event_team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: '',
  },
  {
    memberName: 'Tanishq Mittal',
    memberPost: 'Student_Team',
    memberTeam: 'event_team',
    memberPhoto: '',
    memberRole: '',
    memberDepartment: '',
    memberYear: '',
    memberBranch: '',
    memberInsta: '',
    memberLinkedin: 'https://www.linkedin.com/in/mittal-tanishq/',
  },

];

export { sntTeamMember };
